# Multiple linear regression

## Import the relevant libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

from sklearn.linear_model import LinearRegression

## Load the data

In [2]:
data = pd.read_excel('catalyst_efficiency_multiple.xlsx')
data.head()

efficiency     size  age
0   28.117697   6.4309   41
1   27.429783   6.5622   28
2   33.795160   4.8729   28
3   48.150673  15.0475   33
4   55.040911  12.7546   34

In [3]:
data.describe()

efficiency        size         age
count  100.000000  100.000000  100.000000
mean    35.074736    8.530242   43.300000
std      9.246207    2.979420   11.073218
min     18.513855    4.797500   23.000000
25%     28.113618    6.433300   34.000000
50%     33.670886    6.964050   44.000000
75%     40.286844   10.293225   54.000000
max     60.081735   18.425100   62.000000

## Create multiple linear regression

### Declare the dependent and the independent variables

In [4]:
y = data['efficiency'] # target
x = data[['size', 'age']] # features
x.shape

(100, 2)

### Regression

In [5]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

### Coefficients

In [6]:
reg.coef_

array([2.68498611, 0.03506309])

### Intercept

In [7]:
reg.intercept_

np.float64(10.65292349824902)

### R-squared

In [8]:
reg.score(x,y)

0.7464976047690852

### Adjusted R-squared

Formula for Adjusted R^2

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

where,

$R^2$ is our usual R-squared value, 

$n$ is the number of observations (or also called samples in machine learning language), and

$p$ is the number of features.


Adjusted R-squared for multiple regression

In [9]:
r2 = 0.74649760476908522
n = 100
p = 2

adj_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adj_r2

0.7412707512591694

Adjusted R-squared for simple regression

In [10]:
r2 = 0.74473918658475857
n = 100
p = 1

adj_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adj_r2

0.742134484407052

### Calculate the univariate p-values of the variables

Here's an activity: Familiarize yourself with the f-statistic and the concept of p-values. You can read this informative webpage to understand the f-statistic:https://online.stat.psu.edu/stat501/lesson/6/6.2

In [11]:
from sklearn.feature_selection import f_regression

In [12]:
f_regression(x,y)

(array([2.85921052e+02, 1.15223820e-03]),
 array([8.12763222e-31, 9.72990343e-01]))

In [13]:
p_values = f_regression(x,y)[1]
p_values

array([8.12763222e-31, 9.72990343e-01])

In [14]:
p_values.round(3)

array([0.   , 0.973])

### Create a summary table with your findings

In [15]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['p-values'] = p_values.round(3)
reg_summary

Features  Coefficients  p-values
0     size      2.684986     0.000
1      age      0.035063     0.973